### ISSUE TITLE
Use network_id instead of expecting network name to be in a certain format

### ISSUE THREAD

**Issue by nantrinh** [venice-framework/venice-cli#11]
docker inspect --format='{{range .NetworkSettings.Networks}}{{.NetworkID}}{{end}}' broker-1
to get network id of the broker-1 container

**Comment by mmanousos** [comment]
As it stands, the current approach doesn't rely on any specific container being alive to get the network name. 
The proposed command would require `broker-1` to be alive at all times (which is unreliable).
